### > Aula - 08/09/2021<br>
> Aula: 04 <br>
> Módulo: 00 <br>
> Turma: DSTN07

O objetivo dessa aula é introduzir a biblioteca Numpy.


**Tópicos**:
* Numpy:
 - ndarray
 - Inicialização de Arrays Numpy e Primeiros Passos
 - Criando arrays com funções
 - Manipulação das dimensões de um array
 - Selecionando partes do array

# Numpy (Parte I)

### O que é numpy??

O NumPy é uma poderosa biblioteca Python que é usada principalmente para realizar cálculos em Arrays Multidimensionais. O NumPy fornece um grande conjunto de funções e operações de biblioteca que ajudam os programadores a executar facilmente cálculos numéricos.
Esses tipos de cálculos numéricos são amplamente utilizados em tarefas como:

* Modelos de Machine Learning.
* Processamento de Imagem e Computação Gráfica.
* Tarefas matemáticas.

### O  ndarry

A estrutura de dados mais importante que o NumPy fornece é um objeto poderoso, um tipo de Array, chamada ndarray.<br>

Esse Array NumPy é uma tabela de elementos (geralmente números), todos do mesmo tipo, indexados por uma tupla de inteiros positivos.<br>

O array do módulo numpy é otimizado para grandes volumes de dados, tem uma estrutura interna compacta e realiza várias operações em paralelo. Além disso, o array numpy suporta tipos de dados não numéricos e é possível fazer operações matemáticas sobre todos os seus valores com apenas uma instrução.<br>

### numpy.array é a função para criar um ndarray

Os principais atributos do ndarray são:
* os tipos de dados (dtype) 
* shape
* size
* ndim

In [1]:
import numpy as np

In [2]:
my_array = np.array(((20,23,55),  #usamos a função array do NumPy para criar uma matriz
                     (52,19,21),
                     (38,64,11),
                     (19,15,41)))
print(my_array)

[[20 23 55]
 [52 19 21]
 [38 64 11]
 [19 15 41]]


In [3]:
# Para saber o tipo de dado da matriz podemos recorrer ao atributo dtype
my_array.dtype

dtype('int32')

In [4]:
# para saber o formato de um array temos o atributo shape. Ele retorna uma tupla contendo o formato do array
my_array.shape

(4, 3)

In [5]:
# O atributo size retorna o número de elementos na matriz.
my_array.size

12

In [8]:
# O atributo ndim retornará o número de dimensões da matriz
my_array.ndim

2

#### Desafio 01 - Gere e mostre a matriz transposta da matriz_inicial: (5 min - pesquisem no google)
---

In [9]:
matriz_inicial = np.array([[10, 20, 30],
                           [31, 50, 64],
                           [70, 80, 90],
                           [21, 54, 87]])

# Criando uma mariz Transposta:

In [10]:
matriz_inicial.T

array([[10, 31, 70, 21],
       [20, 50, 80, 54],
       [30, 64, 90, 87]])

### Selecionado partes do array
---

In [ ]:
# para selecionar elementos na matriz podemos usar a seguinte sintaxe
print(my_array[0,2])

In [ ]:
# selecionando apenas a primeira linha
print (my_array[0,:])

In [ ]:
# selecionando apenas a  coluna 2
print(my_array[:,2])

### Criando arrays com funções definidas
---

In [ ]:
# np.zeros: cria um array com todos os elementos sendo 0.
z = np.zeros([4,4], dtype = int)
print(z)

In [ ]:
# np.ones: cria um array com todos os elementos sendo 1.
o = np.ones([4,4], dtype = int)
print(o)

In [ ]:
# np.empty: cria um array cujo conteúdo inicial é aleatório.
e = np.empty([4,4], dtype = int)
print(e)

In [ ]:
# np.identity; cria um array indentidade.
i = np.identity(4, dtype = int)
print(i)

### Manipulação das dimensões de um array
---

Se temos um array de dimensões n x m, podemos aplicar uma reformatação, para que mude suas dimensões sem alterar os dados.
O importante é que o produto n.m seja constante.

Exemplo:

n(numeros de linhas) = 4

m(numero de colunas) = 4

n x m = 16

Possibilidades de reformulação:
    
* 2*8 </n>
* 8*2 </n>
* 1*16 </n>

In [ ]:
my_array = np.array(((33, 12, 93, 21),
                     (17, 26, 11, 90),
                     (23, 18, 16, 22),
                     (48, 23, 97, 19)))
print(my_array)

In [ ]:
# função reshape
my_array_reshaped = np.reshape(my_array, (8,2))
print (my_array_reshaped)

In [ ]:
my_array_reshaped = np.reshape(my_array, (2,8))
print (my_array_reshaped)

In [ ]:
#O comando ravel distorce o array multidimensional e o transforma em um array 1D.
uma_dimensao = my_array_reshaped.ravel()
print(uma_dimensao)

In [ ]:
# Posso ter uma lista e transformá-la
lista = [1,2,3]
print(type(lista))

In [ ]:
# podemos definir o tipo
np_array_da_lista = np.array(lista, int) 
print(np_array_da_lista)

In [ ]:
type(np_array_da_lista)

#### Desafio 02 - For loop em arrays:
---
Print elemento por elemento (utilizando For loop) o seguinte array:

In [22]:
array_exercicio = np.array([[1,2,3],[4,5,6]])

1
2
3
4
5
6


#### Desafio 3 -  Manipulação de matrizes em imagens:
---
Quais os principais atributos do ndarray da imagem abaixo?

In [ ]:
from PIL import Image
im = Image.open("C:/Users/vinicius.sousa.ext/Downloads/sample.png")
im

In [ ]:
# Transformando a imagem em array:
np_im = np.array(im)
np_im

In [ ]:
# Selecionado partes do array:
print("Pixel(0,0):",np_im[0][0])
print("Pixel(419,419):",np_im[419][419])
print("Pixel(839,839):",np_im[839][839])

In [ ]:
# Verificação dos atributos do array da imagem:
print("--- Atributos do array da imagem ---")
print("Type:",np_im.dtype)
print("Shape:",np_im.shape)
print("Size:",np_im.size)
print("Dim:",np_im.ndim)

---
Refaça o desafio com uma imagem menor do que o exemplo e com uma imagem de um icone famoso (Ex: Apple, JBL, ...) e tire as suas concluções das matrizes.